In [158]:
import pandas as pd
import numpy as np

In [181]:
# replace the file name with the name of the file you want to read

file_path = 'final_research_news.csv'
new_file_path = 'dataset/news_categories/research_news1.csv'

In [183]:
# read the csv file and drop the first column
df = pd.read_csv(file_path, index_col=0)
df.head()

,title,date,article_body,link,category
0,BLS International signs contract with the Emba...,28 March,BLS International Services Ltd. has entered in...,https://www.moneycontrol.com/news/business/bls...,Partnership
1,RailTel bags order worth Rs 287.57 crore from ...,15 March,State-owned RailTel Corporation of India Ltd s...,https://www.moneycontrol.com/news/business/rai...,Partnership
2,"Defence ministry inks Rs 6,800-cr contract wit...",07 March,The defence ministry on Tuesday sealed a deal ...,https://www.moneycontrol.com/news/business/def...,Partnership
3,Bajaj Electricals bags Rs 565 cr contract from...,04 March,Bajaj Electricals on Saturday said its EPC div...,https://www.moneycontrol.com/news/business/baj...,Partnership
4,FM Logistic bags contract from UCB,17 January,Third-party logistics service provider FM Logi...,https://www.moneycontrol.com/news/business/fm-...,Partnership

In [161]:
df.columns

Index(['Date_Time', 'Title', 'Full_News', 'Links', 'Category'], dtype='object')

title, date, article_body, link, category, summary, company_name, funds

In [162]:
# rename the columns
df.columns = ['date', 'title', 'article_body', 'link', 'category']
df.head()

,date,title,article_body,link,category
0,28 March,Almost 80% of early-stage startups plan to hir...,"About 80 percent of early-stage startups, with...",https://www.moneycontrol.com/news/business/sta...,Research
1,11 March,88% Indians would trade high-paying jobs for m...,A majority of Indians would rather take a lowe...,https://www.moneycontrol.com/news/trends/88-in...,Research
2,22 February,Dollar hovers near six-week high as economies ...,"The dollar was little changed on Wednesday, co...",https://www.moneycontrol.com/news/business/eco...,Research
3,16 February,91% Indian students feel professional certific...,Ninety-one per cent Indian students believe th...,https://www.moneycontrol.com/news/business/eco...,Research
4,09 February,58% startups believe fund-raising will get tou...,Venture debt firm InnoVen Capital in the eight...,https://www.moneycontrol.com/news/business/sta...,Research

In [163]:
# rearrange the columns as per our requirement: title, date, article_body, link, category
df = df.iloc[:,[1,0,2,3,4]]
df.head()

,title,date,article_body,link,category
0,Almost 80% of early-stage startups plan to hir...,28 March,"About 80 percent of early-stage startups, with...",https://www.moneycontrol.com/news/business/sta...,Research
1,88% Indians would trade high-paying jobs for m...,11 March,A majority of Indians would rather take a lowe...,https://www.moneycontrol.com/news/trends/88-in...,Research
2,Dollar hovers near six-week high as economies ...,22 February,"The dollar was little changed on Wednesday, co...",https://www.moneycontrol.com/news/business/eco...,Research
3,91% Indian students feel professional certific...,16 February,Ninety-one per cent Indian students believe th...,https://www.moneycontrol.com/news/business/eco...,Research
4,58% startups believe fund-raising will get tou...,09 February,Venture debt firm InnoVen Capital in the eight...,https://www.moneycontrol.com/news/business/sta...,Research

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180 entries, 0 to 179
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         180 non-null    object
 1   date          180 non-null    object
 2   article_body  153 non-null    object
 3   link          180 non-null    object
 4   category      180 non-null    object
dtypes: object(5)
memory usage: 8.4+ KB

In [185]:
# summarise the article_body

import nltk
from nltk.corpus import stopwords

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\abhis\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [186]:
# summarise the article_body
# Load Packages
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer


def summarize_data(text):
    parser = PlaintextParser.from_string(text, Tokenizer("english"))
#     print(len(text))
    # Summarize using sumy TextRank
    summarizer = TextRankSummarizer()
    summary = summarizer(parser.document, 2)
    text_summary = ""
    for sentence in summary:
      text_summary += str(sentence)

#     print(len(text_summary))
    return text_summary

In [187]:
sum_data = []
for x in range(0, len(df)):
  if type(df['article_body'][x]) == str:
    summary_output = summarize_data(df['article_body'][x])
    ##print(summary_output)
    ##print(df['Full_News'][x])
    sum_data.append(summary_output)
  else:
    sum_data.append("NaN")


df['summary'] = sum_data
df.head()

,title,date,article_body,link,category,summary
0,BLS International signs contract with the Emba...,28 March,BLS International Services Ltd. has entered in...,https://www.moneycontrol.com/news/business/bls...,Partnership,It operates in the travel services industry an...
1,RailTel bags order worth Rs 287.57 crore from ...,15 March,State-owned RailTel Corporation of India Ltd s...,https://www.moneycontrol.com/news/business/rai...,Partnership,State-owned RailTel Corporation of India Ltd s...
2,"Defence ministry inks Rs 6,800-cr contract wit...",07 March,The defence ministry on Tuesday sealed a deal ...,https://www.moneycontrol.com/news/business/def...,Partnership,"""The ministry of defence on March 7 signed con..."
3,Bajaj Electricals bags Rs 565 cr contract from...,04 March,Bajaj Electricals on Saturday said its EPC div...,https://www.moneycontrol.com/news/business/baj...,Partnership,Bajaj Electricals on Saturday said its EPC div...
4,FM Logistic bags contract from UCB,17 January,Third-party logistics service provider FM Logi...,https://www.moneycontrol.com/news/business/fm-...,Partnership,Third-party logistics service provider FM Logi...

In [188]:
# !pip install -U pip setuptools wheel
# !pip install -U spacy
# !python -m spacy download en_core_web_sm

In [189]:
# finding company name using NER

import spacy

# Load the pre-trained NER model from spaCy
nlp = spacy.load('en_core_web_sm')

In [190]:
# Define a function to extract ORG entities from a text using spaCy
def company_name(text):
    doc = nlp(text)
    orgs = [entity.text for entity in doc.ents if entity.label_ == 'ORG']
    return orgs


org_data = []
for x in range(0, len(df)):
  if type(df['summary'][x]) == str:
    org_output = company_name(df['summary'][x])
    ##print(summary_output)
    ##print(df['Full_News'][x])
    org_data.append(org_output)
  else:
    org_data.append("NaN")
    
df['company_name'] = org_data
df.head()

,title,date,article_body,link,category,summary,company_name
0,BLS International signs contract with the Emba...,28 March,BLS International Services Ltd. has entered in...,https://www.moneycontrol.com/news/business/bls...,Partnership,It operates in the travel services industry an...,"[Business Today Magazine, Forbes Asia, Co-foun..."
1,RailTel bags order worth Rs 287.57 crore from ...,15 March,State-owned RailTel Corporation of India Ltd s...,https://www.moneycontrol.com/news/business/rai...,Partnership,State-owned RailTel Corporation of India Ltd s...,"[State, RailTel Corporation, Centre for Develo..."
2,"Defence ministry inks Rs 6,800-cr contract wit...",07 March,The defence ministry on Tuesday sealed a deal ...,https://www.moneycontrol.com/news/business/def...,Partnership,"""The ministry of defence on March 7 signed con...","[Hindustan Aeronautics Limited, Larsen & Toubr..."
3,Bajaj Electricals bags Rs 565 cr contract from...,04 March,Bajaj Electricals on Saturday said its EPC div...,https://www.moneycontrol.com/news/business/baj...,Partnership,Bajaj Electricals on Saturday said its EPC div...,"[Bajaj Electricals, EPC, South Bihar Power Dis..."
4,FM Logistic bags contract from UCB,17 January,Third-party logistics service provider FM Logi...,https://www.moneycontrol.com/news/business/fm-...,Partnership,Third-party logistics service provider FM Logi...,"[United Colors, UCB, UCB, United Colors]"

In [191]:
# Define a function to extract amount/money/price entities from a text using spaCy

def funds(text):
    doc = nlp(text)
    money = [entity.text for entity in doc.ents if entity.label_ == 'MONEY']
    return money


funds_data = []
for x in range(0, len(df)):
    if type(df['article_body'][x]) == str:
        funds_output = funds(df['article_body'][x])
        ##print(summary_output)
        ##print(df['Full_News'][x])
        funds_data.append(funds_output)
    else:
        funds_data.append("NaN")


df['funds'] = funds_data
df.head()

,title,date,article_body,link,category,summary,company_name,funds
0,BLS International signs contract with the Emba...,28 March,BLS International Services Ltd. has entered in...,https://www.moneycontrol.com/news/business/bls...,Partnership,It operates in the travel services industry an...,"[Business Today Magazine, Forbes Asia, Co-foun...",[]
1,RailTel bags order worth Rs 287.57 crore from ...,15 March,State-owned RailTel Corporation of India Ltd s...,https://www.moneycontrol.com/news/business/rai...,Partnership,State-owned RailTel Corporation of India Ltd s...,"[State, RailTel Corporation, Centre for Develo...",[]
2,"Defence ministry inks Rs 6,800-cr contract wit...",07 March,The defence ministry on Tuesday sealed a deal ...,https://www.moneycontrol.com/news/business/def...,Partnership,"""The ministry of defence on March 7 signed con...","[Hindustan Aeronautics Limited, Larsen & Toubr...","[56 per cent, 60 per cent]"
3,Bajaj Electricals bags Rs 565 cr contract from...,04 March,Bajaj Electricals on Saturday said its EPC div...,https://www.moneycontrol.com/news/business/baj...,Partnership,Bajaj Electricals on Saturday said its EPC div...,"[Bajaj Electricals, EPC, South Bihar Power Dis...",[]
4,FM Logistic bags contract from UCB,17 January,Third-party logistics service provider FM Logi...,https://www.moneycontrol.com/news/business/fm-...,Partnership,Third-party logistics service provider FM Logi...,"[United Colors, UCB, UCB, United Colors]",[]

In [192]:
df.funds.value_counts()

[]                                                                  134
NaN                                                                  27
[$15 million, 15]                                                     1
[USD 24.9 billion]                                                    1
[200]                                                                 1
[USD 2.5 billion, 2.5]                                                1
[USD 11 billion]                                                      1
[USD 16 billion, USD 7.1 billion]                                     1
[USD 8.7 million]                                                     1
[$206.76 million, $690.02 million, $662 million, $27.89 million]      1
[16 per cent, USD 1 billion]                                          1
[Rs 40 billion]                                                       1
[56 per cent, 60 per cent]                                            1
[USD 50 million]                                                      1
[USD 43 million]                                                      1
[USD 14 billion]                                                      1
[multi-million dollar]                                                1
[USD 57 million, approximately USD 57 million]                        1
[USD 57 million]                                                      1
[$130 million]                                                        1
[about USD 19 billion]                                                1
Name: funds, dtype: int64

In [155]:
df.to_csv(new_file_path, index=False)

In [156]:
new_df = pd.read_csv(new_file_path)
new_df.head()

,title,date,article_body,link,category,summary,company_name,funds
0,"ZYNEX ALERT: Bragar Eagel & Squire, P.C. is In...",03/30/2023 - 11:00 PM,NEW YORK--(BUSINESS WIRE)--Bragar Eagel & Squi...,https://www.businesswire.com/news/home/2023033...,Lawsuit News,NEW YORK--(BUSINESS WIRE)--Bragar Eagel & Squi...,"['Eagel & Squire', 'Zynex, Inc.', 'NASDAQ', 'Z...",[]
1,"MARATHON ALERT: Bragar Eagel & Squire, P.C. An...",03/30/2023 - 11:00 PM,NEW YORK--(BUSINESS WIRE)--Bragar Eagel & Squi...,https://www.businesswire.com/news/home/2023033...,Lawsuit News,NEW YORK--(BUSINESS WIRE)--Bragar Eagel & Squi...,"['Eagel & Squire', 'Marathon Digital Holdings,...",[]
2,"Glancy Prongay & Murray LLP, a Leading Securit...",03/30/2023 - 08:56 PM,LOS ANGELES--(BUSINESS WIRE)--Glancy Prongay &...,https://www.businesswire.com/news/home/2023033...,Lawsuit News,LOS ANGELES--(BUSINESS WIRE)--Glancy Prongay &...,"['Prongay & Murray LLP', 'GPM', 'Target Corpor...",[]
3,INVESTOR ALERT: Law Offices of Howard G. Smith...,03/30/2023 - 07:37 PM,"BENSALEM, Pa.--(BUSINESS WIRE)--Law Offices of...",https://www.businesswire.com/news/home/2023033...,Lawsuit News,"BENSALEM, Pa.--(BUSINESS WIRE)--Law Offices of...","['Target Corporation', 'Target', 'NYSE', 'TGT']",[]
4,"Glancy Prongay & Murray LLP, a Leading Securit...",03/30/2023 - 07:28 PM,LOS ANGELES--(BUSINESS WIRE)--Glancy Prongay &...,https://www.businesswire.com/news/home/2023033...,Lawsuit News,LOS ANGELES--(BUSINESS WIRE)--Glancy Prongay &...,"['Prongay & Murray LLP', 'GPM', 'Luminar Techn...",[]